### ISSUE TITLE
freemarker.template.TemplateNotFoundException: Template not found for name "database.html".

### ISSUE THREAD

**Issue by liangjiaying** [enilu/database-doc-generator#7]
```
"C:\Program Files\Java\jdk1.8.0_191\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2019.2\lib\idea_rt.jar=2043:C:\Program Files\JetBrains\IntelliJ IDEA 2019.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_191\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\rt.jar;C:\Users\mscn\IdeaProjects\GitHub\database-doc-generator\target\classes;C:\Java\maven_dependcies\org\nutz\nutz\1.r.66\nutz-1.r.66.jar;C:\Java\maven_dependcies\mysql\mysql-connector-java\5.1.47\mysql-connector-java-5.1.47.jar;C:\Java\maven_dependcies\org\postgresql\postgresql\42.2.5\postgresql-42.2.5.jar;C:\Java\maven_dependcies\com\oracle\ojdbc6\11.2.0.1.0\ojdbc6-11.2.0.1.0.jar;C:\Java\maven_dependcies\org\freemarker\freemarker\2.3.28\freemarker-2.3.28.jar;C:\Java\maven_dependcies\org\apache\poi\poi\3.12\poi-3.12.jar;C:\Java\maven_dependcies\commons-codec\commons-codec\1.9\commons-codec-1.9.jar" cn.enilu.tool.database.doc.generator.Main
19-08-12 22:17:10.327 INFO [main] Select SystemLog as Nutz.Log implement
19-08-12 22:17:10.487 WARN [main] SimpleDataSource is NOT a Connection Pool, So it is slow but safe for debug/study
19-08-12 22:17:10.723 DEBUG [main] Using 101 castor for Castors
19-08-12 22:17:10.786 DEBUG [main] Jdbcs init complete
19-08-12 22:17:10.787 INFO [main] Get Connection from DataSource for JdbcExpert, if you lock at here, check your database server and configure
19-08-12 22:17:12.670 DEBUG [main] select expert : org.nutz.dao.impl.jdbc.oracle.OracleJdbcExpert
19-08-12 22:17:12.709 DEBUG [main] JDBC Driver --> 11.1.0.7.0-Production
19-08-12 22:17:12.709 DEBUG [main] JDBC Name   --> Oracle JDBC driver
19-08-12 22:17:12.709 DEBUG [main] JDBC URL    --> jdbc:oracle:thin:@localhost:1521:orcl
19-08-12 22:17:12.710 DEBUG [main] Database info --> ORACLE:[Oracle - Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options]
19-08-12 22:17:12.779 DEBUG [main] select * from user_tab_comments
19-08-12 22:17:12.864 DEBUG [main] select column_name,data_type,data_length,nullable from user_tab_columns where Table_Name='USERS'
19-08-12 22:17:12.920 DEBUG [main] select column_name,comments from user_col_comments where TABLE_NAME='USERS'
freemarker.template.TemplateNotFoundException: Template not found for name "database.html".
The name was interpreted by this TemplateLoader: LegacyDefaultFileTemplateLoader(baseDir="C:\Users\mscn\IdeaProjects\GitHub\database-doc-generator", canonicalBasePath="C:\Users\mscn\IdeaProjects\GitHub\database-doc-generator\").
Warning: The "template_loader" FreeMarker setting wasn't set (Configuration.setTemplateLoader), and using the default value is most certainly not intended and dangerous, and can be the cause of this error.
	at freemarker.template.Configuration.getTemplate(Configuration.java:2797)
	at freemarker.template.Configuration.getTemplate(Configuration.java:2599)
	at cn.enilu.tool.database.doc.generator.doc.WordGenerator.createDoc(WordGenerator.java:43)
	at cn.enilu.tool.database.doc.generator.database.Generator.generateDoc(Generator.java:54)
	at cn.enilu.tool.database.doc.generator.Main.main(Main.java:92)

Process finished with exit code 0

```

**Comment by itas109** [comment]
src\main\resources\database.html 放到根目录，也就是src的上级目录

**Comment by liangjiaying** [comment]
谢谢



------------------ 原始邮件 ------------------
发件人: "Arron Guo"<notifications@github.com>; 
发送时间: 2019年8月23日(星期五) 凌晨0:13
收件人: "enilu/database-doc-generator"<database-doc-generator@noreply.github.com>; 
抄送: "腾魂龙"<1093055613@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [enilu/database-doc-generator]freemarker.template.TemplateNotFoundException: Template not found for name"database.html". (#7)




src\main\resources\database.html 放到根目录，也就是src的上级目录
